### ISSUE TITLE
Instruction to run training and testing code

### ISSUE THREAD

**Issue by pthai1204** [Adnan1011/caffe#1]
Hi Anana,

Thank for you great work, I have downloaded LIVE dataset. How can I train with that data with your code? Please give step by step to reproduce.

Thanks,
Hai

**Comment by qxconverse** [comment]
Hi Anana,

Thank you for your great work, I have trained one model about fastfading, in your test phrase, you had two output files called: output_.txt and scores_.txt, so how did these files come from? I will be grateful if you could reply me.

Thank you,
Qin

**Comment by Adnan1011** [comment]
I have updated Readme.md with detailed instructions. It lists all the steps.
